# Generated by Django 4.0.6 on 2022-08-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cateforias',
            new_name='categorias',
        ),
    ]
